fix(jobs): upload an initial index file if this is the first release
deis/jenkins-jobs pull request #289
Opened 2016-11-15 23:16 UTC by bacongobbler

When creating a release for the first time, an index file is not present in the bucket to copy and merge from. Therefore in this case we just want to upload an initial index file and call it a day.

Note that this will not help jenkins-node, but will prevent this issue from occurring in the future.

2016-11-15 23:29 UTC, vdice requested changes

2016-11-15 23:29 UTC, vdice commented on jobs/component_chart_publish.groovy
> +              if [ "$(git tag | wc -l)" == "1" ]; then
we need to escape the `$` here (`\$`) b/c it is a shell/runtime resolution as opposed to a groovy/job build-time resolution...

2016-11-15 23:29 UTC, vdice commented
minor change needed; otherwise LGTM!

2016-11-16 00:16 UTC, bacongobbler commented
minor change addressed

2016-11-16 16:25 UTC, vdice approved these changes

2016-11-16 19:01 UTC, kmala approved these changes

2016-11-16 19:11 UTC, bacongobbler commented
The code has been changed to accomodate if the file does not exist, please take a look before this is merged.

The code was thanks to http://stackoverflow.com/a/27003199.

2016-11-16 19:17 UTC, bacongobbler commented
Hold up on this PR. Just a thought, since this job runs when no index file exists, should we run `helm package` initially, upload the index file then re-run `helm package` and merge it with the now-present index? Just wondering if uploading a bare index file when we're releasing a tag of a chart is what we intend.

2016-11-16 19:20 UTC, vdice commented on jobs/component_chart_publish.groovy
> +              if [ "\$(aws s3 ls s3://helm-charts/${repo_chart}/index.yaml | wc -l)" == "0" ]; then
could also use `if [ -z "\$(aws s3 ls s3://helm-charts/${repo_chart}/index.yaml)" ]; then` here -- but just an fyi

2016-11-16 21:33 UTC, vdice commented
> should we run `helm package` initially

@bacongobbler we do a helm package immediately prior, so the first `index.yaml` file _should_ actually be populated... so I think we are good here.  But good concern.

2016-11-16 21:36 UTC, bacongobbler commented on jobs/component_chart_publish.groovy
> +              if [ "\$(aws s3 ls s3://helm-charts/${repo_chart}/index.yaml | wc -l)" == "0" ]; then
done

2016-11-16 21:58 UTC, vdice commented on jobs/component_chart_publish.groovy
> +              if [ -z "\$(aws s3 ls s3://helm-charts/${repo_chart}/index.yaml)" ]; then
ah, also `s/repo_chart/repo.chart`

2016-11-17 16:21 UTC, merged