chore(common.groovy): bump helm to latest
deis/jenkins-jobs pull request #391
Opened 2017-07-03 21:44 UTC by vdice

Requires https://github.com/deis/e2e-runner/pull/102

TODO
 - [ ] test in conjunction w/ aforementioned PR

2017-07-03 22:20 UTC, mboersma approved these changes

2017-08-10 17:56 UTC, bacongobbler requested changes

2017-08-10 17:56 UTC, bacongobbler commented on common.groovy
> +    version: 'v2.5.0',
might want to bump to v2.5.1 instead; there was a few pretty serious bugs in 2.5.0.

https://github.com/kubernetes/helm/releases/tag/v2.5.1

2017-08-10 17:57 UTC, bacongobbler commented
Sorry for the delay on this review btw!

2017-08-30 23:52 UTC, vdice commented
Bumped to latest Helm release `v2.6.0` and tested in conjunction w/ related PR in https://ci.deis.io/job/workflow-chart-e2e/595/console -- I think we should be ready to merge!

2017-09-04 13:55 UTC, mboersma commented
@vdice there's [Helm v2.6.1](https://github.com/kubernetes/helm/releases/tag/v2.6.1) now. But updating Helm for Workflow CI isn't a big priority given this week is the [final monthly release](https://deis.com/blog/2017/deis-workflow-final-release/), so we could also just close this.

2017-09-06 19:54 UTC, merged